development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
 
      database: challenge_development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: challenge_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
